version: "3.8"

services:
  mongodb_server:
    image: mongo:4.4
    command: mongod --serviceExecutor adaptive
    ports:
      - 1231:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin_user
      - MONGO_INITDB_ROOT_PASSWORD=admin_pass

  redis:
    image: 'redis:4-alpine'
    command: redis-server --requirepass 102030
    ports:
      - '1230:6379'

